import { BaseModel } from '../base.model';

export interface RequestCancelOrderModel extends BaseModel {
  stt?: number;
  orderdate: number;
  orderno: string;
  partscode: string;
  partsname: string;
  unitName: string;
  supplierCode: string;
  qty: number;
  price: number;
  rate: number;
  sumPrice: number; //
  status: string;

  countApproval?;
  countCancel?;
  countItem?;
  countNormal?;
  countReq?;
  countSend?;
  countSep?;
  createDate?;
  createdBy?;
  deleteflag?;
  dlrCode?;
  dlrId?;
  dlrName?;
  expressShipping?;
  genuine?;
  initialdate?;
  lastdate?;
  localflag?;
  modifiedBy?;
  cancelstatus?;
  modifyDate?;
  modifyDateHeader?;
  orderDId?;
  orderId?;
  orderMCode?;
  orderMName?;
  ordercancel?;
  ordercanceldate?;
  ordermethodId?;
  orderstatus?;
  orderunit?;
  orderunitnum?;
  partSize?;
  partsId?;
  partstype?;
  partstypeCode?;
  partstypeName?;
  region?;
  reqId?;
  reqtype?;
  sellprice?;
  sellunitCode?;
  sellunitName?;
  sepStatus?;
  seqdisplay?;
  substitutioncode?;
  substitutionpartno?;
  substitutionpartnoOld?;
  supplierName?;
  transportCode?;
  transportName?;
  transportby?;
  unitCode?;
}
