export const GlobalPermission = {
  TMV_MASTER_DATA: [
    'LOGISTICS_MASTER', 'PROVINCES', 'DEALER_OUTLET', 'MODEL_GRADE', 'GASOLINE_ASSIGNMENT_DEALERS', 'YARD_AREA', 'YARD_LOCATION', 'COLORS_MASTER',
    'COLOR_ASSIGNMENT', 'INSURANCE_MASTER', 'TRAINSPORT_VEHICLE_MANAGEMENT', 'YARD_MANAGEMENT', 'DEALER_GROUPS', 'INVOICE_LEAD_TIMES', 'DISTRICTS',
    'BANKS', 'TMV_DAY_OFF_MANAGEMENT', 'GRADE_PRODUCTION', 'PLAN_DELIVERY_DATE_TIME', 'AUDIO_MASTER', 'MONEY_DEFINITION', 'DLR_ADDRESS_RC_VEH'
  ],
  TMV_FLEET_SALE: [
    'FLEET_SALES_BY_TMV', 'FLEET_CUSTOMER'
  ],
  DAILY_SALE: [
    'VEHICLES_ARRIVAL', 'CONTRACT_MANAGEMENT', 'CS_CHANGE_INFORMATION', 'CBU_VEHICLES', 'CKD_VEHICLES', 'CHANGE_DELIVERY'
  ],
  DEALER_ORDER: [
    'DLR_ORDER_SUMARY'
  ],
  TFS: [
    'TFS_PAY_BY', 'TFS_APPROVE'
  ],
  TMV_ADMIN: [
    'CHECK_LOG_VEHICLES', 'SLE_COLUMN_LIST', 'SLE_FORM_COLUMN', 'SLE_GROUP_LIST', 'SLE_S_USER_COLUMN', 'IP_DEALER_CONFIG'
  ],
  REPORT: [
    'P_DEFERENT_DELIVERY_DATE_101', 'CS_CHANGE_INFORMATION', 'P_NO_DELIVERY_DATE', 'P_SPECIAL_CASE_REQUEST_102'
  ],
  SWAPPING: [
    'SWAPPING_VEHICLE', 'DISPATCH_CHANGE_REQUEST', 'TMV_SELL_REPORT', 'STOCK_CAR_AT_DEALER', 'SELL_BUY_MATCHING', 'SWAPPING_SEARCH_VEHICLE',
    'NATIONWIDE_SELLING_LIST', 'NATIONWIDE_BUYING_LIST'
  ],
  DLR_MASTER_DATA: [
    'SALES_PERSON', 'SALES_GROUP', 'DLR_DAY_OFF_MANAGEMENT'
  ],
  DLR_FLEET_SALE: [
    'FLEET_SALES_BY_DLR'
  ]
};
