export const ErrorCodes = {
  // 4xx Common error http
  400: 'Lỗi trong việc truyền dữ liệu lên.',
  403: 'Không có quyền truy cập.',
  404: 'Không tìm thấy API.',
  405: 'Gọi sai METHOD.',
  406: 'Giá trị nhập vào bị trùng.',
  408: 'Connection timeout.',
  409: 'Dữ liệu đã tồn tại trong hệ thống',
  415: 'Dữ liệu đã được sử dụng',
  417: 'Xử lý ở server lỗi.',
  418: 'Người dùng không tồn tại.',
  419: 'ID Đại lý không tồn tại.',
  420: 'Tài khoản bị khóa. Vui lòng liên hệ TMV để biết thêm thông tin.',
  423: '.Nhập sai 5 lần sẽ bị khóa',
  424: 'Mật khẩu không được trùng với 5 lần gần nhất',
  452: 'Trường date phải được nhập.',
  453: 'Ngày nhập phải nhỏ hơn ngày hiện tại.',
  454: 'Ngày nhập phải nhỏ hơn hoặc bằng ngày hiện tại.',
  455: 'Ngày nhập phải lớn hơn ngày hiện tại.',
  456: 'Ngày nhập phải lớn hơn hoặc bằng ngày hiện tại.',
  457: 'Thời gian bắt đầu phải lớn hơn thời gian kết thúc.',
  458: 'Không được nhập khoảng thời gian (ngày) đã áp dụng.',
  470: 'Số phải là số dương.',
  471: 'Số phải là số âm.',
  472: 'Sai định dạng số điện thoại.',
  473: 'Trường phải nhập số.',
  480: 'Sai định dạng email.',
  481: 'Trường phải nhập chữ.',
  482: 'Không được quá số ký tự tối đa.',
  483: 'Không được ít hơn số ký tự tối thiểu.',
  490: 'Định dạng file không đúng.',
  491: 'Mật khẩu chưa chính xác.',
  492: 'Bạn không có quyền truy cập từ [{0}]',

  // 5xx server error
  500: 'Có lỗi xử lý dữ liệu từ server.',
  501: 'Hàm chưa implement.',
  503: 'Server bị gián đoạn.',
  505: 'ID không tồn tại',
  506: 'Có dữ liệu liên kết, không thể xoá.',
  518: 'Không có quyền thay đổi thông tin.',
  520: 'Lỗi khi truy vấn cơ sở dữ liệu.',
  521: 'Mã code đã tồn tại.',
  522: 'Bản ghi đã thay đổi thông tin. Hãy refresh để lấy dữ liệu.',
  523: 'Phiếu hẹn đã có báo giá, không thể thay đổi thông tin',
  524: 'Hẹn đã bị hủy.',
  525: 'Hẹn đã No-show.',
  527: 'Không thể hủy hẹn do đã đặt phụ tùng.',
  529: 'Không thể NoShow do khách hàng đã đặt tiền hoặc đã đặt phụ tùng.',
  530: 'Trạng thái đang là Báo Giá, không thể in Quyết Toán.',
  532: 'Đại lý thiếu config thông số thời gian.',
  571: 'Tên đã bị trùng.',
  580: 'Chưa nhập đủ các trường dữ liệu yêu cầu nhé.',
  582: 'Không thể suggest thời gian tự động cho thời gian hẹn này.',
  583: 'Không tìm thấy bản ghi: {0}, id: {1}',

  // 9xx

  999: 'Fatal error: không thể truy vấn SQL, database lỗi',

  // 10xx
  // Báo giá
  1000: 'Không tìm thấy báo giá',
  1001: 'Đang có RO chưa đóng.',
  1002: 'Không thể xuất phụ tùng cho lệnh sửa chữa này.',
  1003: 'Không thể hoàn thành khi đang ở trạng thái Báo Giá.',
  1004: 'RO đã hoàn thành, không thể thêm phụ tùng.',
  1005: 'RO đã đóng, không thể thêm phụ tùng hoặc công việc.',
  1006: 'Trạng thái chưa thể in quyết toán.',
  1007: 'RO đã hoàn thành, không thể in LXPT.',
  1008: 'Không có phụ tùng hoặc phụ tùng chưa được báo giá.',
  1009: 'RO đã hoàn thành, không thể in LSC.',
  1010: 'RO đã đóng.',
  1011: 'Không thể hoàn thành do xe đang báo giá hoặc chưa sửa chữa xong.',
  421: 'Không thể hoàn thành do xe đang báo giá hoặc chưa sửa chữa xong.',
  1012: 'Không thể Xuất Phụ Tùng do xe đã đưa vào sửa chữa.',
  1013: 'Chưa thể Hoàn Thành do chưa xuất hết phụ tùng.',
  1014: 'Kiểm tra lại danh sách phụ tùng đã khai báo.',
  1015: 'RO đã chuyển sang Lệnh Sửa Chữa.',
  1019: 'Thời gian hẹn cho CVDV đã bị trùng.',
  1021: 'Phiếu hẹn có phụ tùng chưa đặt hàng lên TMV, yêu cầu xóa phụ tùng trước khi hủy hẹn.',
  1022: 'Không tồn tại RO này..',
  1023: 'Bạn không có quyền sửa báo giá này.',
  1024: 'RO không có công việc..',
  1025: 'Trùng mã công việc.',
  1026: 'Không thể hủy RO, đã sang lệnh khác.',
  1030: 'Biển số xe đã tồn tại.',
  1031: 'Đặt hẹn không có trong tiến độ sửa chữa.',
  1032: 'Không thể auto tính toán thời gian giao xe dự kiến.',
  1033: 'Nhập trùng dòng xe, đời xe',
  1035: 'Loại công việc của phiếu hẹn chưa xác định',
  1034: 'Kiểu báo giá sai hoặc không có.',
  1036: 'Thời gian hẹn nhỏ hơn thời gian hiện tại.',
  1037: 'Không thế auto tính thời gian giao xe dự kiến, hãy tự chỉnh trong bảng tiến độ.',
  1038: 'Đã tồn tại thời gian tiến độ gợi ý. Vui lòng điều chỉnh lại bên bảng tiến độ.',
  1039: 'Báo giá không còn ở trạng thái báo giá, không thể đổi thời gian suggest.',
  1040: 'Tồn tại phiếu hẹn trễ trong quá khứ, đề nghị hủy hẹn này.',
  1041: 'Khách đến sớm so với phiếu hẹn, hãy điều chỉnh lại hẹn trong bảng tiến độ.',
  1042: 'Đã có bản ghi trong bảng tiến độ, check bảng tiến độ.',
  1043: 'Sai mã code, mã code chỉ có 2 giá trị 1, 2',
  1044: 'Chỉ có ô lên kế hoạch và ô dừng trong khoang mới có thể nhân đôi.',
  1045: 'Thời gian bắt đầu phải trước thời gian kết thúc.',
  1046: 'Khoang đã có xe trong khoảng thời gian này.',
  1047: 'Không thể lấy thông tin người dùng hiện thời, có lỗi xảy ra',
  1048: 'Chưa có hẹn để dời hẹn.',
  1049: 'Đại lý {0} config không dùng bảng tiến độ',
  1050: 'Chỉ được chọn các bản ghi có cùng biển số',

  // 20xx
  2000: 'Xử lý lỗi.',
  2001: 'Mã đơn hàng đã tồn tại.',
  2002: 'Tạo mã đơn hàng thất bại.',
  2003: 'Không thể điều chỉnh số lượng PT.',
  2004: 'Đơn hàng này đã đóng, bạn không được phép thay đổi.',
  2005: 'Đơn hàng này đã in lệnh xuất pt, bạn không được phép xóa.',
  2006: 'Đơn hàng đã được xử lý, bạn không được phép xóa.',
  2007: 'Đã in Lệnh xuất phụ tùng, không được phép sửa chỉ được thêm thông tin phụ tùng.',
  2008: 'Chỉ được điều chỉnh tăng số lượng.',
  2009: 'Đơn vị mua, khác đơn vị bán, trường hợp này không cho điều chỉnh tăng, dùng phương thức đặt hàng tmv không get.',
  2010: 'Chỉ được điều chỉnh giảm số lượng.',
  2011: 'Phải xóa phụ tùng trước khi xóa order.',
  2012: 'Đã in Lệnh xuất phụ tùng, không được phép sửa chỉ được thêm thông tin phụ tùng.',
  2013: 'Tồn tại phụ tùng Lexus nên không được phép đặt hàng.',
  2014: 'Đơn hàng đang xử lý.',
  2015: 'Số lượng cần ngay không thỏa mãn điều kiên.',
  2016: 'Phải nhập số lượng.',
  2017: 'Trạng thái không được để là: "Đại lý mới hỏi.',
  2018: 'Đơn hàng đã xử lý, không được phép sửa.',
  2019: 'TMV không được xóa, chỉ đại lý mới có quyền  xóa.',
  2020: 'Kế hoạch này đã được xử lý, nên không xóa được.',
  2021: 'Số lượng tồn lớn hơn 0. Không thể đặt hàng BO.',
  2022: 'Số lượng cần đặt BO đã được đặt đủ {qty} phụ tùng.',
  2023: 'Đang có một thao tác gởi đơn hàng BO của RO này. Yêu cầu truy vấn lại dữ liệu và thao tác gởi lại đơn hàng!.',
  2024: 'Đơn hàng đã xử lý nên không thể hủy.',
  2025: 'Không thể xóa phụ tùng của đại lý khác.',
  2026: 'Yêu cầu đặt hẹn chỉ được "Prepick" hoặc "Bỏ Prepick" phụ tùng.',
  2027: 'RO này đã bị hủy nên chỉ có thể "Trả lại" hoặc "Bỏ Prepick" phụ tùng.',
  2028: 'Phụ tùng này chưa "Xuất" nên không thể nhập số lượng "Trả lại". Yêu cầu nhập số lượng xuất khác!.',
  2029: 'Số lượng phụ tùng đã "Xuất" là "||v_Qty||" không thể "Trả lại" quá số lượng đã xuất. Yêu cầu nhập số lượng xuất khác!.',
  2030: 'Loại PT này đã xuất đủ!.',
  2031: 'Số lượng trong kho không đủ để thực hiện lệnh xuất này!',
  2032: 'Số lượng xuất phải nhỏ hơn hoặc bằng số lượng còn thiếu!',
  2033: 'Loại PT này chưa xuất nên không thể nhập giá trị âm!',
  2034: 'Số lượng "Trả lại" không được vượt quá số lượng đã xuất!',
  2035: 'RO đã bị thay đổi trạng thái bởi người dùng khác yêu cầu truy vấn lại dữ liệu để có thể thao tác chức năng này.',
  2036: 'Quá trình thực hiện SHIPPING không thành công. Các thông số về số lượng không thỏa mãn điều kiện. ' +
    'Để thực hiện yêu cầu truy vấn lại dữ liệu và thao tác lại quá trình SHIPPING.',
  2037: 'Quá trình thực hiện SHIPPING không thành công. Dòng bản ghi cần thực hiện SHIPPING không tồn tại trong cơ sở dữ liệu lưu trữ.',
  2038: 'Yêu cầu chọn trạng thái xuất hàng!',
  2039: 'Số lượng xuất lớn hơn không thì trạng thái không được chọn là "Trả lại". Yêu cầu chọn trạng thái khác!',
  2040: 'Số lượng xuất nhỏ hơn không. Yêu cầu chọn trạng thái là "Trả lại"!',
  2041: 'Trạng thái xuất là "Pre-pick". Yêu cầu nhập "Vị trị Pre-pick"!',
  2042: 'Đơn hàng không thỏa mãn điều kiện để thao tác chức năng này.',
  2043: 'Số lượng Pre-pick mới phải nhỏ hơn số lượng Pre-pick trước. Yêu cầu nhập giá trị khác.',
  2044: 'Có lỗi khi trả PT prepick.',
  2045: 'Có lỗi khi xuất PT prepick.',
  2046: 'Có lỗi khi trả hết PT prepick.',
  2047: 'Có lỗi khi xuất hết PT prepick.',
  2048: 'Yêu cầu chọn phụ tùng cần trả.',
  2049: 'Yêu cầu nhập "Vị trị Pre-pick".',
  2050: 'Số lượng còn phải xuất nhỏ hơn 0.',
  2051: 'Số phiếu giao hàng này đã được nhận.',
  2053: 'Bạn phải nhận tối thiểu một mã phụ tùng!',
  2054: 'Kiểm tra lại số đơn hàng. Có người đang nhận hàng.',
  2055: 'Có người đang sử dụng chức năng nhận hàng.',
  2056: 'Kiểm tra lại tổng số lượng của phụ tùng.',
  2057: 'Kiểm tra lại tổng số lượng của phụ tùng.', // (Mã PT: {0}, SL cần: {1}, SL xuất: {2}) (lẤY ĐẦY ĐỦ MESSAGE TRONG LỖI TRẢ VỀ)
  2058: 'Phải in báo giá trước khi Xuất hàng.',
  2059: 'Phụ tùng mới thêm, chưa được in báo giá. Phải in báo giá trước khi in lệnh xuất pt.',
  2060: 'Đơn hàng này đã đóng.',
  2061: 'Chưa xuất phụ tùng, chưa được quyết toán.',
  2062: 'Số lượng xuất khác với số lượng cần, không đóng được đơn hàng.',
  2063: 'Không được phép sửa khi đơn hàng đã xử lý',
  2064: 'Không tìm thấy phụ tùng.',
  2065: 'Đại lý không có quyền sử dụng chức năng này.',
  2066: 'Đại lý chưa được đặt Phụ tùng chuyên biệt Lexus.',
  2067: 'Hãy validate lại file excel!',
  2068: 'Khách hàng này có xe, nên không được sửa thông tin tại đây.',
  2069: 'Phụ tùng có code [{0}] chưa nhận hết.',
  422: 'Phụ tùng có code [{0}] chưa nhận hết.',
  2070: 'Số lương TMV mua lớn hơn số lượng muốn bán',
  2071: 'Số lượng tồn trong kho không đủ số lượng để bán',
  2072: 'Mã phụ tùng đã tồn tại',
  2073: 'TMV không mua phụ tùng này',
  2074: 'Chú ý liên hệ phòng phụ tùng để xử lý mã phụ tùng [{0}] trước khi điều trỉnh s.lượng!',
  2075: 'Chưa nhận/xuất hết phụ tùng.',
  2076: 'Vượt quá số lượng cho phép.',
  425: 'Chưa nhận/xuất hết phụ tùng.',
  // 30xx Bảo hành
  3002: 'Thiếu ngày Line Of Date',

  // 50xx
  5001: 'Mã code đã tồn tại.',
  5002: 'Không thể hủy hẹn.',
  5003: 'Kĩ thuật viên đang được sử dụng ở khoang khác, có chắc muốn đổi sang khoang này không?',
  5004: 'Khoang đang được sử dụng!',
  5005: 'Tài khoản đăng nhập chưa có dữ liệu nhân viên!',
  5006: 'Chỉ được xóa gói với trạng thái là nháp',
  5007: 'Tên chiến dịch đã tồn tại',
  5008: 'Dữ liệu dòng xe không tồn tại',


  // 60xx
  6000: 'Trong khoang có xe đang sửa.',
  6001: 'Trong khoang có xe đang có kế hoạch sửa chữa.',
  6002: 'Trong khoang có xe có kế hoạch sửa chữa trước.',
  6003: 'Thời gian lựa chọn đã thuộc kế hoạch của xe khác.',
  6004: 'Kế hoạch sửa chữa của xe không phải ngày hôm nay.',
  6005: 'Tiến độ đổi không hợp lệ.',
  6006: 'Có công việc đang làm trong khoang.',
  6007: 'Công việc chưa được phân công khoang.',
  6008: 'Công việc chưa được phân công cho kỹ thuật viên.',
  6009: 'Công việc đã được bắt đầu.',
  6010: 'Công việc đã kết thúc.',
  6011: 'Công việc không được kết thúc.',
  6012: 'Quá giờ để thay đổi kế hoạch.',
  6013: 'Hiện đang có xe bên trong khoang.',
  6014: 'Xe đã có kế hoạch.',
  6015: 'Thời gian bắt đầu kế hoạch phải sau thời gian hiện tại.',
  6016: 'Xe chưa kết thúc giai đoạn khác.',
  6017: 'Xe có kế hoạch khác cần thực hiện trước.',
  6018: 'Kĩ thuật viên đang làm việc khác.',
  6019: 'Kỹ thuật viên đã có kế hoạch làm trong khoang thơi gian được chọn.',
  6020: 'Hiện tại không phải thời gian làm việc.',
  6021: 'Báo giá hiện không trong trạng thái để có thể sửa chữa.',
  6022: 'Hiện trong khoang đang không có kỹ thuật viên nào.',
  6023: 'Không thể tạo thêm kế hoạch cho lệnh sửa chữa.',
  6024: 'Kỹ thuật viên hiện đã được đưa ra danh sách nghỉ.',
  6025: 'Kỹ thuật viên đã được đưa vào khoang làm việc.',
  6026: 'Kĩ thuật viên, kế hoạch bắt đầu, kế hoạch kết thúc bắt buộc phải nhập.',
  6027: 'Xe đã có kế hoạch trong khoảng thời gian này ở lệnh sửa chữa khác.',
  6028: 'Xe đang thực hiện lệnh sửa chữa khác.',
  6029: 'Có công việc chưa được bắt đầu.',
  6030: 'Công việc chưa được bắt đầu.',
  6031: 'Không thể thay đổi tiến độ ở phần này.',
  6032: 'Xe đã bắt đầu sửa chữa, không thể giải phóng khỏi bảng tiến độ.',
  6033: 'Có 1 việc không đúng trạng thái.',
  6034: 'Công việc chưa có kế hoạch.',
  6035: 'Khoảng thời gian Từ ngày Đến ngày không được lớn hơn 7 ngày.',
  6036: 'Chỉ có thể thay đổi thời gian của xe đang kế hoạch.',
  6037: 'Công việc không phù hợp với kỹ thuật viên.',
  6039: 'Công việc không thể hoàn thành trước thời gian dự kiến giao xe.',
  6040: 'Xe chưa thực hiện công việc nào.',
  6095: 'Thời gian làm việc của đại lý chưa được thiết lập.',
  6096: 'Xe đã rời khỏi đại lý không được phép cập nhật lại thời gian xe ra.',
  6097: 'Xe chưa ra khỏi đại lý.',
  6098: 'Xe đã được tiếp nhận.',
  6099: 'Xe này vẫn đang trong đại lý.',
  6041: 'Báo giá này đã có trong bảng tiến độ.',
  6042: 'Thời gian sửa chữa không hợp lệ',
  6043: 'Không thể xóa phiếu hẹn đã lên lịch, hãy hủy hẹn ở màn hình phiếu hẹn.',
  6044: 'Không thể hẹn vào ngày nghỉ, hãy chọn 1 ngày khác',
  6045: 'Kế hoạch bị trùng thời gian với chính các kế hoạch còn lại của xe.',
  6046: 'Thời gian bắt đầu quá trễ so với thời gian kết thúc làm việc: {0}',
  6047: 'Không thể thay đổi kế hoạch với thời gian được chọn, xin hãy thử lại',
  6048: 'Phải bắt đầu từ kế hoạch sớm nhất',
  6049: 'Không thể dừng trong khoang do xe đang làm ở kế hoạch khác',
  6050: 'Không thể tiếp tục do xe đang sửa chữa ở kế hoạch khác',
  6051: 'Bạn chưa tạo kế hoạch cho xe ở đồng sơn, không thể hoàn thành danh sách xe chờ.',
  6052: 'Kế hoạch từ {0} đến {1} của xe {2} bị trùng hoặc thời gian bắt đầu sau thời gian hiện tại.',
  6053: 'Không thể tính toán thời gian bắt đầu và kết thúc, xin hãy thực hiện lại.',
  6054: 'Sai state {1} do lỗi hệ thống, đề nghị liên hệ bảo trì hệ thống',
  6055: 'Thời gian dừng phải nằm trong khoảng thời gian bắt đầu xe và hiện tại',
  6056: 'Kế hoạch',
  6057: 'Công đoạn làm việc chưa được chọn',
  6058: 'Xe chưa được chọn khoang',
  6059: 'Đã có kế hoạch cho xe ở công đoạn này',
  6060: 'Trùng mã tổ nhóm đồng sơn',
  6061: 'Đã tồn tại các kế hoạch cho xe này',
  6062: 'Xe này đã có công đoạn đang thực hiện',
  6063: 'Xe chưa được thực hiện việc đồng sơn',
  6064: 'Thời gian hoàn thành xe phải > thời gian bắt đầu xe',
  6065: 'Khoảng thời gian lựa chọn không được lớn hơn 14 ngày',
  6066: 'Xe đang có công đoạn chưa kết thúc',
  6067: 'Không thể thực hiện từ xe hẹn.',
  6068: 'Thời gian lựa chọn đã thuộc công việc của xe khác.',

  // 70xx
  7001: 'Yêu cầu nhập điều kiện tìm kiếm.',
  7002: 'Yêu cầu nhập tối thiểu 3 ký tự biển số xe!',
  7003: 'Yêu cầu nhập tối thiểu 5 ký tự số VIN!',
  7004: 'Chưa in hết hóa đơn của lệnh sửa chữa. Yêu cầu in hóa đơn.',
  7005: 'Còn lệnh sửa chữa khác của xe chưa in hóa đơn!',
  7006: 'Lỗi xử lý dữ liệu!',
  7008: 'Không có bản ghi nào được tạo mới!',
  7009: 'Không xác định thông tin Đại lý hoặc người dùng mở form!',
  7010: 'Còn RO đã quyết toán chưa in hóa đơn!',
  7011: 'Chưa tạo hóa đơn.',

  // 80xx
  8000: 'Thời gian hẹn và thời gian giao xe bị trùng, hết khoang trống.',
  8003: 'Không xác định được thao tác.',
  8004: 'Đang tiếp nhận khách hàng khác.',
  8005: 'Xe đang tiếp nhận.',
  8006: 'Tài khoản đăng nhập chưa có bàn cố vấn dịch vụ',
  8007: 'Xe đang trong quá trình sửa chữa không được ra cổng',


  8008: 'Dữ liệu không hợp lệ',
  8009: 'Work Rate phải lớn hơn 0'

};
